### PR TITLE
User-defined AI for Earth base image

### PR DESCRIPTION
**Pull request by pflickin**
- Modify the base Python image to accept an argument for a custom Ubuntu-based image.
- Modify the Tensorflow example for usage on how to use the new image.

### CODE REVIEW

**Comment by yangsiyu007** [comment]
Thanks Patrick, this is clever and solves the problem well. 

Just for my education, for using a compatible Ubuntu-based custom image as base image, what is the benefit of copying `ai4e_api_tools` over from the base Python image instead of downloading these from a blob storage or GitHub repo? The current method is very clean; I just wanted to know if there was other things from the base Python image that are used.

Let me know if you'd like me to do some testing.

**Comment by bluemellophone** [comment]
@pflickin Ok, sounds good.  Can we get a scaled down version of ./startup.sh that includes only the required tracing scripts?  Is it possible to remove that requirement from startup.sh and use crontab with an @reboot trigger or some other systemd service + a config file?

**Comment by pflickin** [comment]
> @pflickin Ok, sounds good. Can we get a scaled down version of ./startup.sh that includes only the required tracing scripts? Is it possible to remove that requirement from startup.sh and use crontab with an @reboot trigger or some other systemd service + a config file?

@bluemellophone Other than the tracing, the only thing that's in the startup.sh is the supervisord call, which handles restarting failed services, etc.  It's not required and provided as an example only.  You are free to use whatever process control system you would like.

**Comment by pflickin** [comment]
> Thanks Patrick, this is clever and solves the problem well.
> 
> Just for my education, for using a compatible Ubuntu-based custom image as base image, what is the benefit of copying `ai4e_api_tools` over from the base Python image instead of downloading these from a blob storage or GitHub repo? The current method is very clean; I just wanted to know if there was other things from the base Python image that are used.
> 
> Let me know if you'd like me to do some testing.
> 
> I also don't think we mentioned how to adapt this example for GPU in the documentation (basically only two changes: installing `tensorflow-gpu` of the desired version instead of `tensorflow` and starting the docker container with `nvidia-docker` for testing on a GPU equipped VM).

The libraries could be downloaded from blob, etc., but I aimed to keep the Dockerfiles consistent.

The nvidia details need to be added to the TF example, but let's do that in a subsequent PR.

**Pull request merged**
