### PR TITLE
Add the animal detector example.

### PR DESCRIPTION
**Pull request by pflickin**

### CODE REVIEW

**Comment by yangsiyu007** [comment]
The file `model/pipeline.config` is not needed; all the information about the model is contained in the .pb model file.

**Comment by yangsiyu007** [comment]
Question: Previously we had an extra step of building a custom base image based on a desired based image, and then starting from the custom base image in the Dockerfile of a new API. Here, we include this step in the Dockerfile - is this the path forward from now (I like this, no extra step to run elsewhere)?

**Comment by yangsiyu007** [comment]
For installation steps, is it from `./ai4e_api_tools` or from `/ai4e_api_tools` which is where the folder was copied to from the base image? Referring to the three lines starting 
```
# Install Miniconda, Flask, Supervisor, uwsgi
RUN ./ai4e_api_tools/requirements/install-api-hosting-reqs.sh
```

**Comment by yangsiyu007** [comment]
Suggestion to insert the copying API code operation to the end of the copying operations, since all other files are from the template (just a nicer order IMO):

```
# Note: supervisor.conf reflects the location and name of your api code.
COPY ./supervisord.conf /etc/supervisord.conf

# startup.sh is a helper script
COPY ./startup.sh /
RUN chmod +x /startup.sh

COPY ./LocalForwarder.config /lf/

# Copy your API code
COPY ./animal-detector /app/animal-detector/
```

**Comment by yangsiyu007** [comment]
`runserver.py` used to have both `ai4e_app_insights` and `ai4e_app_insights_wrapper` but now just has the later - is this a part of the new version?

**Comment by pflickin** [comment]
> Question: Previously we had an extra step of building a custom base image based on a desired based image, and then starting from the custom base image in the Dockerfile of a new API. Here, we include this step in the Dockerfile - is this the path forward from now on (I like this, no extra step to run elsewhere)?
- Yup, this is the new way.


> Just curious: when "If the number of requests exceeds (changed from exceed) this limit, a 503 is returned to the caller", what is the error message - asking them to retry later?
"Service is busy, please try again later"

> In the decorator where `content_types` is specified, is this checked against the post request's body or files that come with it? Sometimes, there are images etc uploaded while some other parameters are passed in the body's json. I'm manually checking the file types currently, which is sufficient. We should specify what this `content_types` is actually checking (I'm guessing it's checking the request's body?).
Just the body, for now.

> Are all the fields in `@ai4e_service.api_sync_func` required? Or is e.g. `content_max_length` optional? I want to send customized error message for content length so I'm not planning on specifying it there.
Only api_path and methods are required.  I'll make a change in the quickstart doc.

**Pull request merged**
